"""
Execution Tracker — Tool-assisted DOC-3 execution chapter generation

Parses git log, branch status, and progress to generate draft execution reports.
Human reviews and approves before commit to DOC-3.

Usage:
    tracker = ExecutionTracker()
    draft = tracker.generate_draft()
    tracker.present_for_review(draft)
    # Human approves, then:
    tracker.commit_to_doc3(draft)
"""

import subprocess
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional
from pathlib import Path


@dataclass
class IdeaProgress:
    """Represents the implementation progress of a single IDEA"""
    idea_id: str
    title: str
    status: str
    implementation_commit: Optional[str] = None
    last_updated: Optional[datetime] = None
    
    def to_dict(self) -> dict:
        return {
            "idea_id": self.idea_id,
            "title": self.title,
            "status": self.status,
            "implementation_commit": self.implementation_commit,
            "last_updated": self.last_updated.isoformat() if self.last_updated else None,
        }


@dataclass
class SessionLogEntry:
    """A single work session log entry"""
    date: str
    agent_mode: str
    work_done: list[str]
    blockers: list[str] = field(default_factory=list)
    next_steps: list[str] = field(default_factory=list)
    
    def to_markdown(self) -> str:
        lines = [
            f"- **{self.date}** ({self.agent_mode}):",
        ]
        for item in self.work_done:
            lines.append(f"  - {item}")
        if self.blockers:
            lines.append("  - Blockers:")
            for b in self.blockers:
                lines.append(f"    - {b}")
        if self.next_steps:
            lines.append("  - Next steps:")
            for n in self.next_steps:
                lines.append(f"    - {n}")
        return "\n".join(lines)


@dataclass
class ExecutionDraft:
    """Draft execution report generated by the tracker"""
    generated_at: datetime
    ideas: list[IdeaProgress]
    session_logs: list[SessionLogEntry]
    git_summary: dict
    progress_file_state: dict
    doc3_path: str
    
    def to_markdown(self) -> str:
        """Convert draft to markdown format for human review"""
        lines = [
            "# Execution Report Draft",
            "",
            f"**Generated:** {self.generated_at.isoformat()}",
            f"**Source:** DOC-3 at `{self.doc3_path}`",
            "",
            "---",
            "",
            "## IDEA Implementation Status",
            "",
        ]
        
        for idea in self.ideas:
            status_icon = {
                "IMPLEMENTED": "[x]",
                "IN_PROGRESS": "[-]",
                "ACCEPTED": "[ ]",
                "REFINED": "[ ]",
                "REJECTED": "[x]",
            }.get(idea.status, "[ ]")
            
            commit_ref = f" (commit `{idea.implementation_commit}`)" if idea.implementation_commit else ""
            lines.append(f"- {status_icon} **{idea.idea_id}** — {idea.title}{commit_ref}")
        
        lines.extend([
            "",
            "---",
            "",
            "## Session Log",
            "",
        ])
        
        if self.session_logs:
            for entry in self.session_logs:
                lines.append(entry.to_markdown())
                lines.append("")
        else:
            lines.append("_No session logs recorded_")
        
        lines.extend([
            "",
            "---",
            "",
            "## Git Summary",
            "",
            f"- Total commits since last release: {self.git_summary.get('commit_count', 'N/A')}",
            f"- Active branches: {self.git_summary.get('active_branches', 'N/A')}",
            f"- Last release tag: {self.git_summary.get('last_release_tag', 'None')}",
            "",
            "---",
            "",
            "## Review Checklist",
            "",
            "- [ ] All IMPLEMENTED ideas have valid implementation_commit",
            "- [ ] Session logs reflect actual work done",
            "- [ ] No duplicate or conflicting status entries",
            "- [ ] Progress consistent with memory-bank/progress.md",
            "",
            "---",
            "",
            "_This draft was auto-generated. Human review required before commit._",
        ])
        
        return "\n".join(lines)
    
    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at.isoformat(),
            "ideas": [i.to_dict() for i in self.ideas],
            "session_logs": [
                {
                    "date": e.date,
                    "agent_mode": e.agent_mode,
                    "work_done": e.work_done,
                    "blockers": e.blockers,
                    "next_steps": e.next_steps,
                }
                for e in self.session_logs
            ],
            "git_summary": self.git_summary,
            "progress_file_state": self.progress_file_state,
            "doc3_path": self.doc3_path,
        }


class ExecutionTracker:
    """
    Tool-assisted execution tracker for DOC-3 generation.
    
    Generates draft execution reports by:
    1. Parsing git log for commit history
    2. Reading progress.md for idea status
    3. Extracting session logs from execution tracker files
    4. Presenting draft for human review
    5. Committing approved content to DOC-3
    """
    
    def __init__(self, repo_path: str = "."):
        self.repo_path = Path(repo_path)
        self.ideas_backlog_path = self.repo_path / "docs" / "ideas" / "IDEAS-BACKLOG.md"
        self.progress_path = self.repo_path / "memory-bank" / "hot-context" / "progress.md"
        self.doc3_path = self.repo_path / "docs" / "DOC-3-CURRENT.md"
        self.execution_tracker_path = self.repo_path / "docs" / "releases"
    
    def generate_draft(self) -> ExecutionDraft:
        """
        Generate an execution draft by analyzing git, progress, and backlog.
        
        Returns:
            ExecutionDraft ready for human review
        """
        ideas = self._parse_ideas_backlog()
        session_logs = self._extract_session_logs()
        git_summary = self._get_git_summary()
        progress_state = self._read_progress_file()
        
        return ExecutionDraft(
            generated_at=datetime.now(timezone.utc),
            ideas=ideas,
            session_logs=session_logs,
            git_summary=git_summary,
            progress_file_state=progress_state,
            doc3_path=str(self.doc3_path),
        )
    
    def _parse_ideas_backlog(self) -> list[IdeaProgress]:
        """Parse IDEAS-BACKLOG.md to extract idea status"""
        ideas = []
        
        if not self.ideas_backlog_path.exists():
            return ideas
        
        content = self.ideas_backlog_path.read_text(encoding="utf-8")
        
        # Parse markdown table rows
        # Format: | ID | Title | Owner | Created | Status | Category | Priority | Release | Deliverables |
        lines = content.split("\n")
        for line in lines:
            if line.startswith("|") and not line.startswith("|---"):
                parts = [p.strip() for p in line.split("|")]
                if len(parts) >= 6:
                    # Skip header row
                    id_part = parts[1].strip()
                    if id_part.startswith("IDEA-"):
                        idea_id = id_part
                        title = parts[2].strip()
                        status = parts[5].strip().replace("[", "").replace("]", "")
                        
                        # Try to find implementation commit from idea file
                        impl_commit = self._find_implementation_commit(idea_id)
                        
                        ideas.append(IdeaProgress(
                            idea_id=idea_id,
                            title=title,
                            status=status,
                            implementation_commit=impl_commit,
                            last_updated=datetime.now(timezone.utc),
                        ))
        
        return ideas
    
    def _find_implementation_commit(self, idea_id: str) -> Optional[str]:
        """Find implementation_commit from idea file"""
        idea_file = self.repo_path / "docs" / "ideas" / f"{idea_id}-*.md"
        
        # Use glob to find matching file
        for f in self.repo_path.glob(f"docs/ideas/{idea_id}-*.md"):
            if f.is_file():
                content = f.read_text(encoding="utf-8")
                match = re.search(r'implementation_commit:\s*([a-f0-9]+)', content)
                if match:
                    return match.group(1)
        return None
    
    def _extract_session_logs(self) -> list[SessionLogEntry]:
        """Extract session logs from EXECUTION-TRACKER files"""
        logs = []
        
        # Find all execution tracker files
        for tracker_file in self.repo_path.glob("docs/releases/**/EXECUTION-TRACKER*.md"):
            content = tracker_file.read_text(encoding="utf-8")
            
            # Parse session log entries
            # Format: ### Session - YYYY-MM-DD
            entries = re.split(r'^### Session - ', content, flags=re.MULTILINE)
            
            for entry in entries[1:]:  # Skip first (before first header)
                lines = entry.strip().split("\n")
                if not lines:
                    continue
                
                date_str = lines[0].strip()
                
                # Extract work done items (lines starting with - or *)
                work_done = []
                blockers = []
                next_steps = []
                current_section = "work"
                
                for line in lines[1:]:
                    stripped = line.strip()
                    if stripped.startswith("**Work Done:**") or stripped.startswith("- **"):
                        current_section = "work"
                    elif stripped.startswith("**Blockers:**"):
                        current_section = "blockers"
                    elif stripped.startswith("**Next Steps:**"):
                        current_section = "next"
                    elif stripped.startswith("- ") and current_section == "work":
                        work_done.append(stripped[2:])
                    elif stripped.startswith("- ") and current_section == "blockers":
                        blockers.append(stripped[2:])
                    elif stripped.startswith("- ") and current_section == "next":
                        next_steps.append(stripped[2:])
                
                logs.append(SessionLogEntry(
                    date=date_str,
                    agent_mode="Human/AI hybrid",
                    work_done=work_done if work_done else ["General work session"],
                    blockers=blockers,
                    next_steps=next_steps,
                ))
        
        return logs
    
    def _get_git_summary(self) -> dict:
        """Get git summary statistics"""
        summary = {
            "commit_count": 0,
            "active_branches": 0,
            "last_release_tag": None,
        }
        
        try:
            # Get commit count since last release
            result = subprocess.run(
                ["git", "rev-list", "--count", "--ancestry-path", "HEAD"],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                summary["commit_count"] = int(result.stdout.strip())
        except Exception:
            pass
        
        try:
            # Get active branch count
            result = subprocess.run(
                ["git", "branch", "--list", "feature/*", "hotfix/*"],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                summary["active_branches"] = len([l for l in result.stdout.split("\n") if l.strip()])
        except Exception:
            pass
        
        try:
            # Get last release tag
            result = subprocess.run(
                ["git", "describe", "--tags", "--abbrev=0"],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                summary["last_release_tag"] = result.stdout.strip()
        except Exception:
            pass
        
        return summary
    
    def _read_progress_file(self) -> dict:
        """Read progress.md for current state"""
        if not self.progress_path.exists():
            return {"exists": False}
        
        content = self.progress_path.read_text(encoding="utf-8")
        
        # Extract checkbox states
        checkboxes = {}
        for line in content.split("\n"):
            match = re.match(r'\s*-\s*\[([ x\-])\]\s*(.+)', line)
            if match:
                state, description = match.groups()
                checkboxes[description.strip()] = state
        
        return {
            "exists": True,
            "checkboxes": checkboxes,
        }
    
    def present_for_review(self, draft: ExecutionDraft) -> str:
        """
        Present draft for human review.
        
        Returns the markdown content for review.
        """
        return draft.to_markdown()
    
    def commit_to_doc3(self, draft: ExecutionDraft, approved: bool = False) -> bool:
        """
        Commit the approved draft to DOC-3.
        
        Args:
            draft: The approved execution draft
            approved: Must be True to actually commit (safety check)
            
        Returns:
            True if committed successfully, False otherwise
        """
        if not approved:
            print("ERROR: Must pass approved=True to commit. Human review required.")
            return False
        
        # This would write to DOC-3, but since this is a draft generator,
        # we return the content that would be written
        print("Would commit to DOC-3 (simulated — actual commit requires human action)")
        return True
    
    def generate_session_log_entry(
        self,
        agent_mode: str,
        work_done: list[str],
        blockers: list[str] = None,
        next_steps: list[str] = None,
    ) -> SessionLogEntry:
        """
        Generate a new session log entry for the current session.
        
        This is called at end of session per RULE 13.
        """
        return SessionLogEntry(
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            agent_mode=agent_mode,
            work_done=work_done,
            blockers=blockers or [],
            next_steps=next_steps or [],
        )


def main():
    """CLI entry point for testing"""
    tracker = ExecutionTracker()
    draft = tracker.generate_draft()
    
    print("=" * 60)
    print("EXECUTION TRACKER — DRAFT GENERATION")
    print("=" * 60)
    print()
    print(draft.to_markdown())
    print()
    print("=" * 60)
    print("To commit this draft to DOC-3:")
    print("  tracker.commit_to_doc3(draft, approved=True)")
    print("=" * 60)


if __name__ == "__main__":
    main()
